### ISSUE TITLE
[1.12.2] Weird crash

### ISSUE THREAD

**Issue by Ushupiuck** [asiekierka/FoamFix#127] opened 2018-03-25 00:12 UTC
If foamfix, ccl & EnderStorage are installed altogether, this weird crash happens. Removing ES solves the issue, but I have contacted and chatted with @covers1624, but as far as he's concerned not a line of code in ES should affect this. Weird, I know...
[crash-2018-03-24_20.16.06-client.txt](https://github.com/asiekierka/FoamFix/files/1844892/crash-2018-03-24_20.16.06-client.txt)

Tested with Foamfix 0.9.5 (both anarchy & lawful give the exact same crash), forge 2611, ccl 3.1.5.334 & ES 2.4.2.126

here's the foamfix config file, just in case. (changed extension to .txt just so I could upload it here)

[foamfix.txt](https://github.com/asiekierka/FoamFix/files/1844894/foamfix.txt)

**Comment by asiekierka** [comment] 2018-03-25 07:35
Both of your URLs are broken.

**Comment by asiekierka** [comment] 2018-03-25 07:36
First, update Forge. This kind of issue could be caused by a Forge version mismatch.

Second, try without FoamFix. I don't see where FoamFix is implicated in the log, and worse - Lawful also does it.

If that does prevent the crash, try disabling model deduplication. If not, well, not my bug!

**Comment by Ushupiuck** [comment] 2018-03-27 03:02
I especifically tried with forge 2611 after latest (2632 at that moment) had failed, in case of an incompatibility with newer forge...
Without foamfix, it loads normally. **I will try disabling the deduplication** to see if that changes anything.
As for if your bug or not? Time will tell! I leave it up to you & covers to discuss that part of the topic, since I'm no modder.

**Comment by Ushupiuck** [comment] 2018-03-30 20:45
@asiekierka, On another test, I managed to reproduce this on another random environment. by my tests, it is related to deduplication recursivity: the default number (6) is fine. however, if you set it to 10 or above (not sure if one below too) this crash occurs. you can reproduce this by setting the config yourself with the mods provided above... and also verify it not crashing when set to default (6).
Excuse the delay btw, the uni has been keeping me busy

**Comment by asiekierka** [comment] 2018-08-11 07:18
Fixed in 0.10.0.

**Closed as completed by asiekierka** 2018-08-11 07:18 UTC
