### ISSUE TITLE
Foamfix Crash on 1.10.2

### ISSUE THREAD

**Issue by HenrikoMagnifico** [asiekierka/FoamFix#69] opened 2017-08-06 14:12 UTC
It crashes whenever I boot the game, sorry guys :P (the game doesn't crash when Foamfix is not in the mods folder) https://pastebin.com/bVehStVF

**Comment by asiekierka** [comment] 2017-08-06 14:15
Duplicate of https://github.com/asiekierka/FoamFix/issues/65 - please move discussion there

Could you please try to disable B:parallelModelBaking?

**Closed as completed by asiekierka** 2017-08-06 14:15 UTC
Labels: duplicate

**Comment by HenrikoMagnifico** [comment] 2017-08-06 14:26
Ah, sorry about the duplicate. I tried disabling B:parallelModelBaking but it still crashed; https://pastebin.com/vc3gUwjA
