### ISSUE TITLE
Most likely reported all ready

### ISSUE THREAD

**Issue by ghost** [asiekierka/FoamFix#173] opened 2018-09-06 20:12 UTC
Ran into this crash again 

https://github.com/SpongePowered/SpongeForge/issues/2432

**Comment by asiekierka** [comment] 2018-09-06 21:15
>Contact them to get the appropriate version of their product that works fine with us.

*squints*

Duplicate of https://github.com/asiekierka/FoamFix/issues/166

**Closed as completed by asiekierka** 2018-09-06 21:15 UTC
Labels: duplicate
