### ISSUE TITLE
0.8.2 Causes my FPS to drop to 0

### ISSUE THREAD

**Issue by NosajDraw** [asiekierka/FoamFix#94] opened 2017-12-01 16:40 UTC
0.8.1 everything was fine.

Running on
Ubuntu 17.10
Nvidia GTX1070

No idea what else to tell you, let me know what details to give

**Comment by asiekierka** [comment] 2017-12-08 23:10
Yeah, apparently things which increase FPS by up to 40-50% on AMD cards don't do the same on nVidia cards. Bleh.

Will work around this in 0.8.3.

**Comment by asiekierka** [comment] 2017-12-09 22:59
Duplicate of https://github.com/asiekierka/FoamFix/issues/92

**Closed as completed by asiekierka** 2017-12-09 22:59 UTC
Labels: duplicate
