### ISSUE TITLE
BetterFoliage Mod Doesn't Work Any Function While FF Beta4 Installed

### ISSUE THREAD

**Issue by kenijey** [asiekierka/FoamFix#45] opened 2017-04-06 19:08 UTC
https://github.com/octarine-noise/BetterFoliage/issues/123
need help... please help... thanks...
it works with parallel model baking disabled...

**Comment by asiekierka** [comment] 2017-04-06 19:14
Yes, it works with parallel model baking disabled.

Duplicate of https://github.com/asiekierka/FoamFix/issues/44

**Comment by kenijey** [comment] 2017-04-06 19:14
yeah i was nearly close this issue :D

**Closed by asiekierka** 2017-04-06 19:14 UTC
