### ISSUE TITLE
crash when loading world

### ISSUE THREAD

**Issue by ghost** [asiekierka/FoamFix#198] opened 2019-04-02 23:36 UTC
https://pastebin.com/WHvxSVQm

Generating a world is fine. When it tries to load it, it crashes.

**Comment by noobanidus** [comment] 2019-04-02 23:52
I'm having the same issue as Wafflemancer is having here and as someone else appears to be having below. There's also a link to a crash report in the comments of the CurseForge page. Here is my crash: https://gist.github.com/duely/5c740bfe652effdd65b5bfa891c289a7

Here also is a list of mods: https://gist.github.com/duely/c2242be9eafb31a8fa762fd869c84e02

This does not include the override mods: [Arcane Archives 2.0.0-preview10](https://github.com/AranaiRa/ArcaneArchives/), which does not use core mods, as far as I'm aware; MagnetRings by Escapee (unsure of the source location); [Mystical World](https://github.com/EpicSquid/MysticalWorld), [MysticalLib](https://github.com/EpicSquid/MysticalLib) and [Roots 3](https://github.com/EpicSquid/Roots) (latest preview builds), along with [my own modpack helper mod, SAC](https://github.com/duely/SAC).

I realise your issue report requests reproducing it with FoamFix-only, but I feel as though this is an issue where code from FoamFix is being overwritten by code from another mod. Hopefully getting a wide sample of the mods common to each of the affected clients will give you a better indication as to which mod might possibly be to blame.

**Comment by Shybella** [comment] 2019-04-02 23:56
https://github.com/asiekierka/FoamFix/issues/197

**Comment by asiekierka** [comment] 2019-04-04 15:51
Duplicate of #197.

**Closed as completed by asiekierka** 2019-04-04 15:51 UTC
Labels: duplicate
