### ISSUE TITLE
Minecraft 10.2 using Foamfix Anarchy Conflicts with PokeCube 

### ISSUE THREAD

**Issue by Oxosorrel** [asiekierka/FoamFix#64] opened 2017-07-09 23:22 UTC
Using Forge 1.10.2-12.18.3.227
Latest Pokecube mods
Pokecube Core 4.24.2
Pokecube Mobs 2.5.1
Pokecube Revival 4.15.8
thutcore 3.14.0

No other mods installed for this test besides foamfix.

What is expected, when first creating a world, prompted with a GUI to select starter pokemon. A model of that pokemon is prominently displayed center left of the UI. After selecting, an item is placed in your inventory that is a pokeball of that pokemon. Random pokemon then spawn in the world, and can be battled and captured with pokeballs (or rather cubes)

This works properly without foamfix.

Behavior is different between Foamfix variants.
Using Foamfix 0.7.1-anarchy
The GUI to select the pokemob appears, but no model of the pokemon is rendered.
After selecting a pokemon starter, no pokeball with the starter is given to the player.
No pokemobs spawn in the world, ever.
No crash is created, so no crashlog.

Foamfix 0.7.1-law
Pokecube functions as per expected, will use law variant for continued play.

Are there particular logs you need generated?

**Comment by asiekierka** [comment] 2017-07-09 23:46
Try disabling (one-by-one, then combinations to get desired functionality working) fasterEntityDataManager. fasterEntityLookup, deduplicateModels - probably in that order.

**Comment by Oxosorrel** [comment] 2017-07-10 02:52
fasterEntityDataManager was the setting that fixed it, thanks.

**Comment by asiekierka** [comment] 2017-07-10 06:26
Nonono. This is a bug.

**Comment by asiekierka** [comment] 2017-08-04 21:31
Duplicate of https://github.com/asiekierka/FoamFix/issues/66

**Closed as completed by asiekierka** 2017-08-04 21:31 UTC
Labels: bug
