### ISSUE TITLE
evilcraft recipes broken by foamfix  

### ISSUE THREAD

**Issue by ApostolosRisen** [asiekierka/FoamFix#226] opened 2019-07-29 20:17 UTC
so with foamfix installed the broom part recipes are broken even with the newest version of both mods, why this happens is beyond my level of coding skill or understanding, if you could look into it for me that would be wonderful

**Comment by rubensworks** [comment] 2019-08-02 13:02
Link to the original issue: https://github.com/CyclopsMC/EvilCraft/issues/782

Some background: EvilCraft fetches recipes by output stack. For some reason, foamfix seems to break this behaviour. I assume the problem is related to NBT-sensitive recipes, as all EvilCraft's broom parts are the same item, but have different NBT tags.

**Comment by ApostolosRisen** [comment] 2019-08-02 14:52
So what if anything can be done to correct this issue

**Comment by asiekierka** [comment] 2019-10-07 07:22
Should be fixed in FoamFix 0.10.6.

**Closed as completed by asiekierka** 2019-10-07 07:22 UTC
