### ISSUE TITLE
[1.10.2] NoClassDeffError crash whilst loading Client

### ISSUE THREAD

**Issue by Morpheus1101** [asiekierka/FoamFix#43] opened 2017-04-05 22:02 UTC
I have the ParallellModelBaking set to false, however this still occurs. Log @ https://puu.sh/vaymo/0ef973b551.txt

FF v *beta3
Forge *.2254

**Comment by Morpheus1101** [comment] 2017-04-05 22:44
Looking at this more closely, i think this may be caused by Dark's surge mod

**Comment by asiekierka** [comment] 2017-04-06 09:06
Duplicate of https://github.com/asiekierka/FoamFix/issues/41

**Closed by asiekierka** 2017-04-06 09:06 UTC
